// Interface automatically generated by schemas-to-ts

import { Link } from '../../primitives/interfaces/Link';
import { Media } from '../../../common/schemas-to-ts/Media';
import { Link_Plain } from '../../primitives/interfaces/Link';
import { Link_NoRelations } from '../../primitives/interfaces/Link';

export interface DecoratedContent {
  mainContent?: string;
  subContent?: string;
  links: Link[];
  media?: { data: Media };
}
export interface DecoratedContent_Plain {
  mainContent?: string;
  subContent?: string;
  links: Link_Plain[];
  media?: Media;
}

export interface DecoratedContent_NoRelations {
  mainContent?: string;
  subContent?: string;
  links: Link_NoRelations[];
  media?: number;
}

