// Interface automatically generated by schemas-to-ts

import { Text } from '../../primitives/interfaces/Text';
import { Link } from '../../primitives/interfaces/Link';
import { Text_Plain } from '../../primitives/interfaces/Text';
import { Link_Plain } from '../../primitives/interfaces/Link';
import { Text_NoRelations } from '../../primitives/interfaces/Text';
import { Link_NoRelations } from '../../primitives/interfaces/Link';

export interface Hero {
  mainTagline?: string;
  animatedText: Text[];
  negativeTopMargin?: boolean;
  caption?: string;
  links: Link[];
  fullScreenHeight: boolean;
  imageLinks: Link[];
}
export interface Hero_Plain {
  mainTagline?: string;
  animatedText: Text_Plain[];
  negativeTopMargin?: boolean;
  caption?: string;
  links: Link_Plain[];
  fullScreenHeight: boolean;
  imageLinks: Link_Plain[];
}

export interface Hero_NoRelations {
  mainTagline?: string;
  animatedText: Text_NoRelations[];
  negativeTopMargin?: boolean;
  caption?: string;
  links: Link_NoRelations[];
  fullScreenHeight: boolean;
  imageLinks: Link_NoRelations[];
}

