// Interface automatically generated by schemas-to-ts

export interface SampleContentBlock {
  title?: string;
  description?: string;
  content?: string;
}
export interface SampleContentBlock_Plain {
  title?: string;
  description?: string;
  content?: string;
}

export interface SampleContentBlock_NoRelations {
  title?: string;
  description?: string;
  content?: string;
}

