// Interface automatically generated by schemas-to-ts

import { Menu } from '../../../../components/components/interfaces/Menu';
import { Menu_Plain } from '../../../../components/components/interfaces/Menu';
import { Menu_NoRelations } from '../../../../components/components/interfaces/Menu';

export interface Site {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    Title?: string;
    header_menu: Menu[];
  };
}
export interface Site_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Title?: string;
  header_menu: Menu_Plain[];
}

export interface Site_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Title?: string;
  header_menu: Menu_NoRelations[];
}

export interface Site_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Title?: string;
  header_menu: Menu_Plain[];
}
