// Interface automatically generated by schemas-to-ts

import { Link } from '../../primitives/interfaces/Link';
import { Menu } from './Menu';
import { Link_Plain } from '../../primitives/interfaces/Link';
import { Menu_Plain } from './Menu';
import { Link_NoRelations } from '../../primitives/interfaces/Link';
import { Menu_NoRelations } from './Menu';

export interface NestedMenu {
  main_link?: Link;
  submenus: Menu[];
}
export interface NestedMenu_Plain {
  main_link?: Link_Plain;
  submenus: Menu_Plain[];
}

export interface NestedMenu_NoRelations {
  main_link?: Link_NoRelations;
  submenus: Menu_NoRelations[];
}

