// Interface automatically generated by schemas-to-ts

import { Link } from '../../primitives/interfaces/Link';
import { Link_Plain } from '../../primitives/interfaces/Link';
import { Link_NoRelations } from '../../primitives/interfaces/Link';

export interface NestedMenu {
  main_link?: Link;
}
export interface NestedMenu_Plain {
  main_link?: Link_Plain;
}

export interface NestedMenu_NoRelations {
  main_link?: Link_NoRelations;
}

