// Interface automatically generated by schemas-to-ts

export interface Link {
  label?: string;
  href?: string;
}
export interface Link_Plain {
  label?: string;
  href?: string;
}

export interface Link_NoRelations {
  label?: string;
  href?: string;
}

