// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Icon {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    media: { data: Media };
    name?: string;
  };
}
export interface Icon_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  media: Media;
  name?: string;
}

export interface Icon_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  media: number;
  name?: string;
}

export interface Icon_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  media: AdminPanelRelationPropertyModification<Media>;
  name?: string;
}
