// Interface automatically generated by schemas-to-ts

import { NewsArticle } from '../../../api/news-article/content-types/news-article/news-article';
import { Link } from '../../primitives/interfaces/Link';
import { NewsArticle_Plain } from '../../../api/news-article/content-types/news-article/news-article';
import { Link_Plain } from '../../primitives/interfaces/Link';
import { Link_NoRelations } from '../../primitives/interfaces/Link';

export enum Mode {
  MostRecent = 'most_recent',
  Featured = 'featured',}

export interface ArticleCarousel {
  title?: string;
  mode?: Mode;
  featured_articles: { data: NewsArticle[] };
  limit: number;
  links: Link[];
  hideHeader?: boolean;
}
export interface ArticleCarousel_Plain {
  title?: string;
  mode?: Mode;
  featured_articles: NewsArticle_Plain[];
  limit: number;
  links: Link_Plain[];
  hideHeader?: boolean;
}

export interface ArticleCarousel_NoRelations {
  title?: string;
  mode?: Mode;
  featured_articles: number[];
  limit: number;
  links: Link_NoRelations[];
  hideHeader?: boolean;
}

