// Interface automatically generated by schemas-to-ts

import { Link } from '../../primitives/interfaces/Link';
import { Link_Plain } from '../../primitives/interfaces/Link';
import { Link_NoRelations } from '../../primitives/interfaces/Link';

export interface PageHero {
  title?: string;
  caption?: string;
  links: Link[];
  negativeTopMargin?: boolean;
}
export interface PageHero_Plain {
  title?: string;
  caption?: string;
  links: Link_Plain[];
  negativeTopMargin?: boolean;
}

export interface PageHero_NoRelations {
  title?: string;
  caption?: string;
  links: Link_NoRelations[];
  negativeTopMargin?: boolean;
}

