// Interface automatically generated by schemas-to-ts

import { Icon } from '../../../api/icon/content-types/icon/icon';
import { Media } from '../../../common/schemas-to-ts/Media';
import { Icon_Plain } from '../../../api/icon/content-types/icon/icon';

export interface Link {
  label?: string;
  href?: string;
  icon?: { data: Icon };
  image?: { data: Media };
}
export interface Link_Plain {
  label?: string;
  href?: string;
  icon?: Icon_Plain;
  image?: Media;
}

export interface Link_NoRelations {
  label?: string;
  href?: string;
  icon?: number;
  image?: number;
}

