// Interface automatically generated by schemas-to-ts

import { Link } from './Link';
import { Link_Plain } from './Link';
import { Link_NoRelations } from './Link';

export interface Menu {
  item: Link[];
}
export interface Menu_Plain {
  item: Link_Plain[];
}

export interface Menu_NoRelations {
  item: Link_NoRelations[];
}

