// Interface automatically generated by schemas-to-ts

export interface Text {
  value?: string;
}
export interface Text_Plain {
  value?: string;
}

export interface Text_NoRelations {
  value?: string;
}

