// Interface automatically generated by schemas-to-ts

import { Link } from '../../primitives/interfaces/Link';
import { Icon } from '../../../api/icon/content-types/icon/icon';
import { Link_Plain } from '../../primitives/interfaces/Link';
import { Icon_Plain } from '../../../api/icon/content-types/icon/icon';
import { Link_NoRelations } from '../../primitives/interfaces/Link';

export interface Menu {
  sub_links: Link[];
  label?: string;
  href?: string;
  icon?: { data: Icon };
}
export interface Menu_Plain {
  sub_links: Link_Plain[];
  label?: string;
  href?: string;
  icon?: Icon_Plain;
}

export interface Menu_NoRelations {
  sub_links: Link_NoRelations[];
  label?: string;
  href?: string;
  icon?: number;
}

